# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Blog
tagline:          'Hooray'
description:      'An absolutely awesome blog!'
#url:              http://hyde.getpoole.com
baseurl:          /hyde/

author:
  name:           'K L'
  url:            https://twitter.com/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
